name: data
on:
  schedule:
    - cron: 0 0 1 1 1
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./scripts/scraper-post-process.ts
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://forum.obsidian.md/t/dataview-plugin-snippet-showcase/13673
          downloaded_filename: dataview-plugin-snippet-showcase.html
          postprocess: ./scripts/scraper-post-process.ts
