name: scrape-scripts
on:
  push:
    branches:
      - action-test-branch
jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: peterjgrainger/action-create-branch@v2.0.1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'scripts-updated'
